### ISSUE TITLE
Feature request: Write cache to disk and load on startup

### ISSUE THREAD

**Issue by Zedjones** [mtrdp642/PokeApiNet#18]
I'm using this API to write a program where I really only need to fetch certain data once (specifically, all Pokemon, moves, and the moves' information), and was wondering if there would be a way to make it so that you can write the disk to cache and load it back if it exists? I know I could use a database for this but it seems overly complex to do so given that I'd have to write special logic for the foreign keys. I'd be willing to implement this if you could point me to where I should look to do it.

**Comment by mtrdp642** [comment]
This feature sounds like it would be out-of-scope for the library itself to solve and would be better if handled by the consumer due to the many possible ways the data on the disk could be organized and used. Many questions come up when trying to consider the possible ways to configure this feature (when do we write data to disk, where is data written, what format and which fields do we include, when does the data 'expire', etc). Depending on your use case, this shouldn't be too difficult to implement in your application as all data is easily de/serialized. Possible options:

- Include the data needed within a .json file within your application and read the file in as needed. The data the API provides doesn't change often, so this could work well to provide the needed data without needing to make an external HTTP call, while still providing a (somewhat) easy way of updating the data file itself, if needed.
- The use of a database could be too much overhead depending on the scope of your application, but this problem is exactly what databases are meant to solve - persistent data. Since you control the database, you can define your own schema to make accessing the data within easy.

I'd be happy to help flesh out how these options can be implemented for your use case, but this isn't a feature that I think makes sense to include in this library.

**Comment by Zedjones** [comment]
Yeah, on further inspection, you're definitely right. It shouldn't be too hard to extract the information I need from the models in the library and store them in a database, the Entity Framework should work fine for this. I'll probably use something like SQLite since it's a fairly small data set and will be loaded into memory when the application starts anyway. 

I also didn't realize that you were using a native caching solution (I'm fairly new to C#/.NET) with the MemoryCache, where the whole point is that it can be cleared if needed so there's no guarantee that you could even write all the data necessary to disk. 

Thanks for taking the time to respond!
