### ISSUE TITLE
Big images of DreamWorld and Official Artwork

### ISSUE THREAD

**Issue by Schinwinkwinsky** [mtrdp642/PokeApiNet#32]
Hello, everybody

At PokeApi is available new Sprites that are not being get by PokeApiNet. The images are bigger and I'm developing a Dotnet Maui app to study and I miss those images. Can I try a Pull Request to update PokemonSprite class?

**Comment by mtrdp642** [comment]
Of course! PRs are always welcome for any changes, especially for updates of new API features.

**Comment by Schinwinkwinsky** [comment]
Sure!

**Comment by Schinwinkwinsky** [comment]
Hi, @mtrdp642 

I did the update and my branch is ready. I think I'm not able to push my branch. Can you help with that.

**Comment by Schinwinkwinsky** [comment]
I did some tests using the library directly on my project. I can get the big images now.

**Comment by mtrdp642** [comment]
> Hi, @mtrdp642 
> 
> I did the update and my branch is ready. I think I'm not able to push my branch. Can you help with that.
> 

Github's flow for creating a PR may be different than what you're used to. 

You have to fork this repository, and then create a branch in your fork with the fix. Once pushed, you can then create a PR from your fork into the main repo.

No one but myself has permissions to create a branch in this repository, which is why forks are needed.

**Comment by Schinwinkwinsky** [comment]
Hi, @mtrdp642 

I saw the PR was merged on master. Do you know when a new nuget package will be available?

**Comment by mtrdp642** [comment]
Sorry for the delay in getting the next release out with your contribution. It's available in NuGet now for use. And thanks again!
